mqtt:
  enabled: false

database:
  path: /media/frigate/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://be9c11b486ba0e2b8ea13338d4cc66ee

ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    amcrest_mt2544ew_01_main:
      - "rtsp://{FRIGATE_AMCREST_MT2544EW_01_USER}:{FRIGATE_AMCREST_MT2544EW_01_PASSWORD}@192.168.1.120:554/cam/realmonitor?channel=1&subtype=0"
    amcrest_mt2544ew_01_sub:
      - "rtsp://{FRIGATE_AMCREST_MT2544EW_01_USER}:{FRIGATE_AMCREST_MT2544EW_01_PASSWORD}@192.168.1.120:554/cam/realmonitor?channel=1&subtype=1"
    amcrest_mt2544ew_02_main:
      - "rtsp://{FRIGATE_AMCREST_MT2544EW_02_USER}:{FRIGATE_AMCREST_MT2544EW_02_PASSWORD}@192.168.1.121:554/cam/realmonitor?channel=1&subtype=0"
    amcrest_mt2544ew_02_sub:
      - "rtsp://{FRIGATE_AMCREST_MT2544EW_02_USER}:{FRIGATE_AMCREST_MT2544EW_02_PASSWORD}@192.168.1.121:554/cam/realmonitor?channel=1&subtype=1"
    amcrest_2493e_03_main:
      - "rtsp://{FRIGATE_AMCREST_2493E_03_USER}:{FRIGATE_AMCREST_2493E_03_PASSWORD}@192.168.1.122:554/cam/realmonitor?channel=1&subtype=0"
    amcrest_2493e_03_sub:
      - "rtsp://{FRIGATE_AMCREST_2493E_03_USER}:{FRIGATE_AMCREST_2493E_03_PASSWORD}@192.168.1.122:554/cam/realmonitor?channel=1&subtype=1"
    anpviz_ptz_06_main:
      - "rtsp://{FRIGATE_ANPVIZ_PTZ_06_USER}:{FRIGATE_ANPVIZ_PTZ_06_PASSWORD}@192.168.1.175:554/Streaming/Channels/101"
    anpviz_ptz_06_sub:
      - "rtsp://{FRIGATE_ANPVIZ_PTZ_06_USER}:{FRIGATE_ANPVIZ_PTZ_06_PASSWORD}@192.168.1.175:554/Streaming/Channels/102"

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 7
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30

objects:
  track:
    - person
    - face
    - license_plate
    - car
    - motorcycle
    - bicycle
    - school_bus
    - dog
    - cat
    - bird
    - deer
    - cow
    - horse
    - goat
    - package
    - amazon
    - fedex
    - ups
    - usps
  filters:
    person:
      min_score: 0.65
      threshold: 0.85
    car:
      min_score: 0.65
      threshold: 0.85
    motorcycle:
      min_score: 0.65
      threshold: 0.85
    bicycle:
      min_score: 0.65
      threshold: 0.85
    school_bus:
      min_score: 0.65
      threshold: 0.85
    dog:
      min_score: 0.7
      threshold: 0.9
    cat:
      min_score: 0.65
      threshold: 0.8
    bird:
      min_score: 0.65
      threshold: 0.85
    deer:
      min_score: 0.7
      threshold: 0.85
    cow:
      min_score: 0.7
      threshold: 0.85
    horse:
      min_score: 0.7
      threshold: 0.85
    goat:
      min_score: 0.7
      threshold: 0.85
    package:
      min_score: 0.65
      threshold: 0.9
    face:
      min_score: 0.7
    license_plate:
      min_score: 0.6
    amazon:
      min_score: 0.75
    fedex:
      min_score: 0.75
    ups:
      min_score: 0.75
    usps:
      min_score: 0.75

birdseye:
  enabled: false
  mode: objects

cameras:
  amcrest_mt2544ew_01:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/amcrest_mt2544ew_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/amcrest_mt2544ew_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 1
    live:
      streams:
        main_stream: amcrest_mt2544ew_01_main
        sub_stream: amcrest_mt2544ew_01_sub
    ui:
      order: 10

  amcrest_mt2544ew_02:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/amcrest_mt2544ew_02_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/amcrest_mt2544ew_02_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 1
    live:
      streams:
        main_stream: amcrest_mt2544ew_02_main
        sub_stream: amcrest_mt2544ew_02_sub
    ui:
      order: 20

  amcrest_2493e_03:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/amcrest_2493e_03_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/amcrest_2493e_03_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 1
    live:
      streams:
        main_stream: amcrest_2493e_03_main
        sub_stream: amcrest_2493e_03_sub
    ui:
      order: 30

  amcrest_mt2544e_04:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/amcrest_mt2544e_04_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: false
      fps: 5
    live:
      streams:
        main_stream: amcrest_mt2544e_04_main
    ui:
      order: 40

  amcrest_mt2544e_05:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/amcrest_mt2544e_05_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      enabled: false
      fps: 5
    live:
      streams:
        main_stream: amcrest_mt2544e_05_main
    ui:
      order: 50

  anpviz_ptz_06:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/anpviz_ptz_06_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/anpviz_ptz_06_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 352
      height: 240
      fps: 1
    live:
      streams:
        main_stream: anpviz_ptz_06_main
        sub_stream: anpviz_ptz_06_sub
    ui:
      order: 60

  anpviz_ptz_07:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/anpviz_ptz_07_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/anpviz_ptz_07_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
      width: 352
      height: 240
      fps: 5
    live:
      streams:
        main_stream: anpviz_ptz_07_main
        sub_stream: anpviz_ptz_07_sub
    ui:
      order: 70

  anpviz_ptz_08:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/anpviz_ptz_08_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/anpviz_ptz_08_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
      width: 352
      height: 240
      fps: 5
    live:
      streams:
        main_stream: anpviz_ptz_08_main
        sub_stream: anpviz_ptz_08_sub
    ui:
      order: 80

  hikvision_ptz_09:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hikvision_ptz_09_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hikvision_ptz_09_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
      width: 352
      height: 240
      fps: 5
    live:
      streams:
        main_stream: hikvision_ptz_09_main
        sub_stream: hikvision_ptz_09_sub
    ui:
      order: 90
